### PR TITLE
Create RN UI Customization interface

### PR DESCRIPTION
**Pull request by jaimepark-stripe**
Copied the UI customization iOS files from https://github.com/getbouncer/react-native-cardverify/tree/master/ios to create a UI customization interface for `react-native-cardscan`.

PR for API doc https://github.com/getbouncer/apidocs/pull/67

### CODE REVIEW

**Review by kingst-stripe — COMMENTED** [review]
Do you have a plan to make sure that this doesn't impact current integrations? The code looks find I just want to make sure that we don't end up breaking people's stuff

**Comment by jaimepark-stripe** [comment]
I didn't change the existing `scan` RN interface and I didn't update any of the dependencies so I feel like we should be fine

**Comment by kingst-stripe** [comment]
For the `cardverify` version there was an app that was customizing button text in objective C and our customizations broke their integration, you may be right but this one case is something that's worth thinking about

**Review by kingst-stripe — APPROVED** [review]
Ship it. Can you bump it to version `2.0.0` to signify to people that this is a major change?

**Pull request merged**
